const squareRoot = require("./exceptions")

// test ran just fine
test("Square root of 4 is 2", () => {
  expect(squareRoot(4)).toBe(2)
})
